US STATES HEALTH ANALYSIS

In [5]:
import pandas as pd
import numpy as np
import matplotlib as mpl

Creating dataframes for all the csv files to be Analysed and merged after cleaning

In [21]:
diverse_states_df = pd.read_csv('diverse_states.csv')
expensive_states_df = pd.read_csv('expensive_states_healthcare.csv')
health_care_costs_by_state_df = pd.read_csv('healthcare_costs_share_of_income_by_state.csv')
healthcare_spending_per_person_df = pd.read_csv('healthcare_spending_per_person_by_state.csv')
healthiest_states_df = pd.read_csv('healthiest_states.csv')
life_expectancy_by_state_df = pd.read_csv('life_expectancy_by_state.csv')
obesity_rate_df = pd.read_csv('obesity_rates_in_US_States.csv')

Read the DataFrame Data

Diversity Index representing the probability that two people chosen at random will be of different racial or ethnic backgrounds

In [9]:
diverse_states_df.head(10)

   Rank             State  Diversity Index (%)
0     1            Hawaii                 76.0
1     2        California                 69.7
2     3            Nevada                 68.8
3     4          Maryland                 67.3
4     5  Washington, D.C.                 67.2
5     6             Texas                 67.0
6     7        New Jersey                 65.8
7     8          New York                 65.8
8     9           Georgia                 64.1
9    10           Florida                 64.1

Healthcare cost index in 2026, with the national average set at 100.

In [10]:
expensive_states_df.head(10)

   Rank                 State  Healthcare Cost Index (U.S. = 100)
0     1         Massachusetts                               131.8
1     2                Alaska                               130.7
2     3  District of Columbia                               118.7
3     4            New Jersey                               115.8
4     5                Oregon                               115.3
5     6                 Maine                               114.7
6     7                Hawaii                               113.1
7     8             Minnesota                               111.5
8     9            California                               111.1
9    10            Washington                               110.3

Health care expenses as a share of median monthly household income across America

In [20]:
health_care_costs_by_state_df.head(10)

   Rank           State Health Care as % of Household Income
0     1          Alaska                               10.08%
1     2          Oregon                                9.32%
2     3           Maine                                9.30%
3     4     Mississippi                                9.18%
4     5   West Virginia                                9.14%
5     6      New Mexico                                9.07%
6     7  North Carolina                                8.78%
7     8         Montana                                8.62%
8     9    South Dakota                                8.60%
9    10       Louisiana                                8.13%

Per-capita health care spending in America

In [23]:
healthcare_spending_per_person_df.head(10)

   Rank                 State Per-Capita Health Care Spending
0     1                Alaska                         $14,044
1     2  District of Columbia                         $13,865
2     3          South Dakota                         $12,451
3     4              New York                         $12,221
4     5         West Virginia                         $12,055
5     6              Delaware                         $11,987
6     7         Massachusetts                         $11,985
7     8          North Dakota                         $11,667
8     9               Vermont                         $11,493
9    10               Indiana                         $11,071

Healthiest States in America using 99 indicators such as economic hardship, smoking rates, and mortality rates measured in z-scores, with a score of 0 representing the national average.

In [14]:
healthiest_states_df.head(10)

   Rank          State  Overall Score 2025
0     1  New Hampshire                0.99
1     2  Massachusetts                0.91
2     3        Vermont                0.91
3     4    Connecticut                0.68
4     5           Utah                0.64
5     6      Minnesota                0.63
6     7     Washington                0.61
7     8       Maryland                0.59
8     9         Hawaii                0.54
9    10   Rhode Island                0.51

US life expectancy

In [15]:
life_expectancy_by_state_df.head(10)

   Rank          State  Life Expectancy (Years)
0     1         Hawaii                     80.0
1     2  Massachusetts                     79.8
2     3     New Jersey                     79.6
3     4       New York                     79.5
4     5    Connecticut                     79.4
5     6     California                     79.3
6     7      Minnesota                     79.3
7     8   Rhode Island                     79.2
8     9           Utah                     79.0
9    10  New Hampshire                     78.7

Percentage of adults with a body mass index (BMI) of 30 or higher across all 50 states and U.S. territories.

In [16]:
obesity_rate_df.head(10)

  Rank State or Territory Adult Obesity Rate (2024)
0    1      West Virginia                     41.4%
1    2        Mississippi                     40.4%
2    3               Guam                     40.2%
3    4          Louisiana                     39.2%
4    5         Tennessee*                     38.9%
5    6            Alabama                     38.9%
6    7           Arkansas                     38.9%
7    8            Indiana                     38.4%
8    9     Virgin Islands                     37.7%
9   10             Kansas                     37.6%