US STATES HEALTH ANALYSIS

In [19]:
import pandas as pd
import numpy as np
import matplotlib as mpl
%matplotlib inline
from functools import reduce

Creating dataframes for all the csv files to be Analysed and merged after cleaning

In [20]:
diverse_states_df = pd.read_csv('diverse_states.csv')
expensive_states_df = pd.read_csv('expensive_states_healthcare.csv')
health_care_costs_by_state_df = pd.read_csv('healthcare_costs_share_of_income_by_state.csv')
healthcare_spending_per_person_df = pd.read_csv('healthcare_spending_per_person_by_state.csv')
healthiest_states_df = pd.read_csv('healthiest_states.csv')
life_expectancy_by_state_df = pd.read_csv('life_expectancy_by_state.csv')
obesity_rate_df = pd.read_csv('obesity_rates_in_US_States.csv')

In [21]:
obesity_rate_df.rename(columns={'State or Territory': 'State'}, inplace=True) # Changed column name for merging

Creating a sorted list of dataframes to prepare for merging

In [24]:
dfs = [diverse_states_df, expensive_states_df, health_care_costs_by_state_df, healthcare_spending_per_person_df,
       healthiest_states_df, life_expectancy_by_state_df, obesity_rate_df]

Dropping duplicate column on the dataframes to prevent suffix errors while merging

In [33]:
dfs = [df.drop('Rank', axis=1) for df in dfs]

Merging on the State column

In [34]:
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['State'], how='outer', suffixes=('_left', '_right')), dfs)

In [ ]:
Viewing merged dataframe

In [35]:
df_merged.head(10)

,State,Diversity Index (%),Healthcare Cost Index (U.S. = 100),Health Care as % of Household Income,Per-Capita Health Care Spending,Overall Score 2025,Life Expectancy (Years),Adult Obesity Rate (2024)
0,Alabama,53.1,85.6,7.32%,"$7,980",-0.75,73.8,38.9%
1,Alaska,62.8,130.7,10.08%,"$14,044",-0.13,75.8,34.0%
2,Arizona,61.5,98.8,6.81%,"$8,556",-0.06,76.7,33.3%
3,Arkansas,49.8,85.8,7.67%,"$8,562",-0.83,73.9,38.9%
4,California,69.7,111.1,5.64%,"$11,054",0.10,79.3,29.1%
5,Colorado,52.3,103.9,6.05%,"$8,871",0.51,78.5,25.0%
6,Connecticut,55.7,108.9,6.89%,"$10,639",0.68,79.4,32.0%
7,Delaware,59.6,101.6,6.66%,"$11,987",0.23,76.5,36.6%
8,District of Columbia,NaN,118.7,NaN,"$13,865",NaN,76.6,25.5%
9,Florida,64.1,101.4,6.05%,"$9,545",-0.05,77.9,29.6%

Diversity Index representing the probability that two people chosen at random will be of different racial or ethnic backgrounds

In [36]:
df_merged.tail(10)

,State,Diversity Index (%),Healthcare Cost Index (U.S. = 100),Health Care as % of Household Income,Per-Capita Health Care Spending,Overall Score 2025,Life Expectancy (Years),Adult Obesity Rate (2024)
47,Utah,40.7,89.9,5.11%,"$7,233",0.64,79.0,31.0%
48,Vermont,20.2,108.2,7.98%,"$11,493",0.91,78.3,29.0%
49,Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,37.7%
50,Virginia,60.5,96.9,5.62%,"$9,123",0.40,77.5,32.3%
51,Washington,55.9,110.3,7.01%,"$9,693",0.61,78.4,31.5%
52,"Washington, D.C.",67.2,NaN,NaN,NaN,NaN,NaN,NaN
53,West Virginia,20.2,89.5,9.14%,"$12,055",-0.73,72.2,41.4%
54,Wisconsin,37.0,105.3,6.76%,"$10,079",0.16,78.1,37.4%
55,Wyoming,32.4,97.0,7.84%,"$9,640",-0.04,76.8,32.5%
56,🇺🇸 U.S. State and Territory Average,NaN,NaN,NaN,NaN,NaN,NaN,34.1%