US STATES HEALTH ANALYSIS

In [105]:
import re
import pandas as pd
import numpy as np
import matplotlib as mpl
%matplotlib inline
from functools import reduce

Creating dataframes for all the csv files to be Analysed and merged after cleaning

In [106]:
pd.set_option("display.max.columns", None)

In [107]:
diverse_states_df = pd.read_csv('diverse_states.csv')
expensive_states_df = pd.read_csv('expensive_states_healthcare.csv')
health_care_costs_by_state_df = pd.read_csv('healthcare_costs_share_of_income_by_state.csv')
healthcare_spending_per_person_df = pd.read_csv('healthcare_spending_per_person_by_state.csv')
healthiest_states_df = pd.read_csv('healthiest_states.csv')
life_expectancy_by_state_df = pd.read_csv('life_expectancy_by_state.csv')
obesity_rate_df = pd.read_csv('obesity_rates_in_US_States.csv')

In [108]:
obesity_rate_df.rename(columns={'State or Territory': 'State'}, inplace=True) # Changed column name for merging

Creating a sorted list of dataframes to prepare for merging

In [109]:
dfs = [diverse_states_df, expensive_states_df, health_care_costs_by_state_df, healthcare_spending_per_person_df,
       healthiest_states_df, life_expectancy_by_state_df, obesity_rate_df]

Dropping duplicate column on the dataframes to prevent suffix errors while merging

In [110]:
dfs = [df.drop('Rank', axis=1) for df in dfs]

Merging on the State column

In [111]:
df_merged = reduce(lambda  left, right: pd.merge(left, right, on=['State'], how='outer', suffixes=('_left', '_right')), dfs)

Viewing merged dataframe

In [112]:
df_merged.head()

,State,Diversity Index (%),Healthcare Cost Index (U.S. = 100),Health Care as % of Household Income,Per-Capita Health Care Spending,Overall Score 2025,Life Expectancy (Years),Adult Obesity Rate (2024)
0,Alabama,53.1,85.6,7.32%,"$7,980",-0.75,73.8,38.9%
1,Alaska,62.8,130.7,10.08%,"$14,044",-0.13,75.8,34.0%
2,Arizona,61.5,98.8,6.81%,"$8,556",-0.06,76.7,33.3%
3,Arkansas,49.8,85.8,7.67%,"$8,562",-0.83,73.9,38.9%
4,California,69.7,111.1,5.64%,"$11,054",0.10,79.3,29.1%

In [113]:
df_merged.tail()

,State,Diversity Index (%),Healthcare Cost Index (U.S. = 100),Health Care as % of Household Income,Per-Capita Health Care Spending,Overall Score 2025,Life Expectancy (Years),Adult Obesity Rate (2024)
52,"Washington, D.C.",67.2,NaN,NaN,NaN,NaN,NaN,NaN
53,West Virginia,20.2,89.5,9.14%,"$12,055",-0.73,72.2,41.4%
54,Wisconsin,37.0,105.3,6.76%,"$10,079",0.16,78.1,37.4%
55,Wyoming,32.4,97.0,7.84%,"$9,640",-0.04,76.8,32.5%
56,🇺🇸 U.S. State and Territory Average,NaN,NaN,NaN,NaN,NaN,NaN,34.1%

In [114]:
df_merged.rename(columns={'Overall Score 2025': 'Health Score', 'Adult Obesity Rate (2024)': 'Adult Obesity (%)', 
                          'Per-Capita Health Care Spending':'Per-Capita Health Care Spending ($)'},
                 inplace=True) # Changed column names to properly reflect column data

In [115]:
df_merged.head()

,State,Diversity Index (%),Healthcare Cost Index (U.S. = 100),Health Care as % of Household Income,Per-Capita Health Care Spending ($),Health Score,Life Expectancy (Years),Adult Obesity (%)
0,Alabama,53.1,85.6,7.32%,"$7,980",-0.75,73.8,38.9%
1,Alaska,62.8,130.7,10.08%,"$14,044",-0.13,75.8,34.0%
2,Arizona,61.5,98.8,6.81%,"$8,556",-0.06,76.7,33.3%
3,Arkansas,49.8,85.8,7.67%,"$8,562",-0.83,73.9,38.9%
4,California,69.7,111.1,5.64%,"$11,054",0.10,79.3,29.1%

Removing %, $ and commas using regex from the column data for Visualization

In [116]:
df_merged.replace(r"(^\$)|(%$)|(\,)", '', regex=True, inplace=True)

,State,Diversity Index (%),Healthcare Cost Index (U.S. = 100),Health Care as % of Household Income,Per-Capita Health Care Spending ($),Health Score,Life Expectancy (Years),Adult Obesity (%)
0,Alabama,53.1,85.6,7.32,7980,-0.75,73.8,38.9
1,Alaska,62.8,130.7,10.08,14044,-0.13,75.8,34.0
2,Arizona,61.5,98.8,6.81,8556,-0.06,76.7,33.3
3,Arkansas,49.8,85.8,7.67,8562,-0.83,73.9,38.9
4,California,69.7,111.1,5.64,11054,0.10,79.3,29.1
5,Colorado,52.3,103.9,6.05,8871,0.51,78.5,25.0
6,Connecticut,55.7,108.9,6.89,10639,0.68,79.4,32.0
7,Delaware,59.6,101.6,6.66,11987,0.23,76.5,36.6
8,District of Columbia,NaN,118.7,NaN,13865,NaN,76.6,25.5
9,Florida,64.1,101.4,6.05,9545,-0.05,77.9,29.6
10,Georgia,64.1,99.6,6.62,8680,-0.27,75.9,35.4
11,Guam,NaN,NaN,NaN,NaN,NaN,NaN,40.2
12,Hawaii,76.0,113.1,8.00,9808,0.54,80.0,27.0
13,Idaho,35.9,101.6,7.82,8078,0.26,78.4,32.7
14,Illinois,60.3,103.0,7.71,9895,-0.03,77.5,34.2
15,Indiana,41.3,91.5,6.64,11071,-0.21,75.4,38.4
16,Iowa,30.8,94.3,6.74,8660,0.24,77.9,36.6
17,Kansas,45.4,90.6,7.19,9066,0.03,76.5,37.6
18,Kentucky,32.8,92.4,7.46,9964,-0.50,73.6,37.2
19,Louisiana,58.6,91.6,8.13,10148,-0.94,73.8,39.2
20,Maine,18.5,114.7,9.30,10913,0.47,76.6,33.2
21,Maryland,67.3,106.9,6.76,9456,0.59,77.8,32.7
22,Massachusetts,51.6,131.8,8.00,11985,0.91,79.8,27.0
23,Michigan,45.2,88.2,6.65,9023,-0.08,76.8,36.1
24,Minnesota,40.5,111.5,6.09,10567,0.63,79.3,32.3
25,Mississippi,55.9,85.1,9.18,8135,-0.77,72.6,40.4
26,Missouri,40.8,98.0,7.43,10036,-0.29,75.2,34.6
27,Montana,30.1,106.3,8.62,9747,-0.05,77.3,31.0
28,Nebraska,40.8,105.6,6.87,10192,0.20,78.3,37.6
29,Nevada,68.8,105.4,5.87,7536,-0.39,76.4,34.2
30,New Hampshire,23.6,106.5,6.42,10682,0.99,78.7,31.1
31,New Jersey,65.8,115.8,5.81,10468,0.51,79.6,27.7
32,New Mexico,63.0,101.9,9.07,8469,-0.37,74.5,34.5
33,New York,65.8,108.9,7.98,12221,0.09,79.5,29.5
34,North Carolina,57.9,108.4,8.78,8744,0.13,75.9,34.5
35,North Dakota,32.6,107.7,8.08,11667,0.37,77.9,36.8
36,Ohio,40.4,96.5,6.68,10202,-0.11,75.6,36.9
37,Oklahoma,59.5,98.1,7.51,9052,-0.62,73.8,36.8
38,Oregon,46.1,115.3,9.32,9931,0.21,77.7,33.5
39,Pennsylvania,44.0,95.1,6.80,10262,0.07,77.3,34.2
40,Puerto Rico,NaN,NaN,NaN,NaN,NaN,NaN,36.2
41,Rhode Island,49.4,104.1,6.09,9864,0.51,79.2,31.1
42,South Carolina,54.6,97.6,6.13,7741,-0.18,75.1,34.6
43,South Dakota,35.6,104.1,8.60,12451,0.12,77.3,37.0
44,Tennessee,46.6,88.7,6.77,8761,-0.55,73.8,NaN
45,Tennessee*,NaN,NaN,NaN,NaN,NaN,NaN,38.9
46,Texas,67.0,96.8,6.77,7807,-0.32,77.1,35.6
47,Utah,40.7,89.9,5.11,7233,0.64,79.0,31.0
48,Vermont,20.2,108.2,7.98,11493,0.91,78.3,29.0
49,Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,37.7
50,Virginia,60.5,96.9,5.62,9123,0.40,77.5,32.3
51,Washington,55.9,110.3,7.01,9693,0.61,78.4,31.5
52,Washington D.C.,67.2,NaN,NaN,NaN,NaN,NaN,NaN
53,West Virginia,20.2,89.5,9.14,12055,-0.73,72.2,41.4
54,Wisconsin,37.0,105.3,6.76,10079,0.16,78.1,37.4
55,Wyoming,32.4,97.0,7.84,9640,-0.04,76.8,32.5
56,🇺🇸 U.S. State and Territory Average,NaN,NaN,NaN,NaN,NaN,NaN,34.1

Merging and grouping split Tennessee Data

In [117]:
df_merged["State"] = df_merged["State"].str.replace("*", "", regex=False)
df = df_merged.groupby("State", as_index=False).first()

In [118]:
df.head()

,State,Diversity Index (%),Healthcare Cost Index (U.S. = 100),Health Care as % of Household Income,Per-Capita Health Care Spending ($),Health Score,Life Expectancy (Years),Adult Obesity (%)
0,Alabama,53.1,85.6,7.32,7980,-0.75,73.8,38.9
1,Alaska,62.8,130.7,10.08,14044,-0.13,75.8,34.0
2,Arizona,61.5,98.8,6.81,8556,-0.06,76.7,33.3
3,Arkansas,49.8,85.8,7.67,8562,-0.83,73.9,38.9
4,California,69.7,111.1,5.64,11054,0.10,79.3,29.1

Final compiled CSV output

In [119]:
df.to_csv('final_data.csv', sep=',', index=False, encoding='utf-8', na_rep='NaN')

Understanding the DataFrame

In [120]:
df.columns

Index(['State', 'Diversity Index (%)', 'Healthcare Cost Index (U.S. = 100)',
       'Health Care as % of Household Income',
       'Per-Capita Health Care Spending ($)', 'Health Score',
       'Life Expectancy (Years)', 'Adult Obesity (%)'],
      dtype='str')

In [121]:
df.dtypes

State                                       str
Diversity Index (%)                     float64
Healthcare Cost Index (U.S. = 100)      float64
Health Care as % of Household Income        str
Per-Capita Health Care Spending ($)         str
Health Score                            float64
Life Expectancy (Years)                 float64
Adult Obesity (%)                           str
dtype: object

Convert str Columns to float

In [122]:
df['Health Care as % of Household Income'] = df['Health Care as % of Household Income'].astype('float64')
df['Per-Capita Health Care Spending ($)'] = df['Per-Capita Health Care Spending ($)'].astype('float64')
df['Adult Obesity (%)'] = df['Adult Obesity (%)'].astype('float64')

In [123]:
df.dtypes

State                                       str
Diversity Index (%)                     float64
Healthcare Cost Index (U.S. = 100)      float64
Health Care as % of Household Income    float64
Per-Capita Health Care Spending ($)     float64
Health Score                            float64
Life Expectancy (Years)                 float64
Adult Obesity (%)                       float64
dtype: object

In [124]:
df.describe()

,Diversity Index (%),Healthcare Cost Index (U.S. = 100),Health Care as % of Household Income,Per-Capita Health Care Spending ($),Health Score,Life Expectancy (Years),Adult Obesity (%)
count,51.000000,51.000000,50.000000,51.000000,50.000000,51.000000,55.000000
mean,49.398039,102.358824,7.290400,9915.705882,0.056800,76.878431,34.114545
std,14.598445,10.398580,1.133749,1531.949468,0.479496,1.998130,3.878785
min,18.500000,85.100000,5.110000,7233.000000,-0.940000,72.200000,25.000000
25%,40.450000,95.800000,6.642500,8752.500000,-0.255000,75.700000,31.750000
50%,51.600000,101.900000,6.950000,9864.000000,0.080000,77.300000,34.200000
75%,61.000000,108.300000,7.995000,10660.500000,0.452500,78.350000,36.950000
max,76.000000,131.800000,10.080000,14044.000000,0.990000,80.000000,41.400000

In [125]:
df.count()

State                                   56
Diversity Index (%)                     51
Healthcare Cost Index (U.S. = 100)      51
Health Care as % of Household Income    50
Per-Capita Health Care Spending ($)     51
Health Score                            50
Life Expectancy (Years)                 51
Adult Obesity (%)                       55
dtype: int64

In [126]:
df.isnull().sum()

State                                   0
Diversity Index (%)                     5
Healthcare Cost Index (U.S. = 100)      5
Health Care as % of Household Income    6
Per-Capita Health Care Spending ($)     5
Health Score                            6
Life Expectancy (Years)                 5
Adult Obesity (%)                       1
dtype: int64

Filling NaN with Median for data estimation

In [127]:
numeric_cols = df.select_dtypes(include="number").columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

In [128]:
df.head()

,State,Diversity Index (%),Healthcare Cost Index (U.S. = 100),Health Care as % of Household Income,Per-Capita Health Care Spending ($),Health Score,Life Expectancy (Years),Adult Obesity (%)
0,Alabama,53.1,85.6,7.32,7980.0,-0.75,73.8,38.9
1,Alaska,62.8,130.7,10.08,14044.0,-0.13,75.8,34.0
2,Arizona,61.5,98.8,6.81,8556.0,-0.06,76.7,33.3
3,Arkansas,49.8,85.8,7.67,8562.0,-0.83,73.9,38.9
4,California,69.7,111.1,5.64,11054.0,0.10,79.3,29.1

In [130]:
df.to_csv('final_data(Filled NaN).csv', sep=',', index=False, encoding='utf-8')